const CACHE = 'arshavin-grade4-v14';
const CORE = [
  './','./index.html','./assets/css/site.css','./assets/js/learning-shell.js',
  './assets/js/sleep-lesson.js','./assets/js/bones-posture-lesson.js','./assets/js/muscles-movement-lesson.js','./assets/js/breathing-air-lesson.js','./assets/js/ai-claims-lesson.js','./assets/js/privacy-consent-lesson.js','./assets/js/data-bias-lesson.js','./assets/js/pm25-lesson.js','./assets/js/water-cycle-lesson.js','./assets/js/levers-lesson.js','./assets/js/pulleys-gears-lesson.js','./assets/js/citizenship-lesson.js','./assets/js/community-decisions-lesson.js',
  './subjects/human-body/sleep-ready-brain.html','./subjects/human-body/bones-joints-safer-posture.html','./subjects/human-body/muscles-rest-movement.html','./subjects/human-body/breathing-gas-exchange-safer-air.html','./subjects/ai-science/fact-opinion-ai-claims.html','./subjects/ai-science/personal-data-digital-footprints-consent.html','./subjects/ai-science/learning-from-data-and-bias.html','./subjects/environment/pm25-safer-action.html','./subjects/environment/water-cycle-responsible-use.html','./subjects/maker-engineering/levers-make-work-easier.html','./subjects/maker-engineering/pulleys-gears-transfer-force.html','./subjects/citizenship/rights-responsibilities-digital-kindness.html','./subjects/citizenship/community-rules-shared-decisions.html',
  './worksheets/student/sleep-ready-brain-a4.html','./worksheets/student/bones-joints-safer-posture-a4.html','./worksheets/student/muscles-rest-movement-a4.html','./worksheets/student/breathing-gas-exchange-safer-air-a4.html','./worksheets/student/fact-opinion-ai-claims-a4.html','./worksheets/student/personal-data-digital-footprints-consent-a4.html','./worksheets/student/learning-from-data-and-bias-a4.html','./worksheets/student/pm25-safer-action-a4.html','./worksheets/student/water-cycle-responsible-use-a4.html','./worksheets/student/levers-make-work-easier-a4.html','./worksheets/student/pulleys-gears-transfer-force-a4.html','./worksheets/student/rights-responsibilities-digital-kindness-a4.html','./worksheets/student/community-rules-shared-decisions-a4.html',
  './worksheets/teacher-guides/bones-joints-safer-posture-guide.html','./worksheets/teacher-guides/muscles-rest-movement-guide.html','./worksheets/teacher-guides/breathing-gas-exchange-safer-air-guide.html','./worksheets/teacher-guides/fact-opinion-ai-claims-guide.html','./worksheets/teacher-guides/personal-data-digital-footprints-consent-guide.html','./worksheets/teacher-guides/learning-from-data-and-bias-guide.html','./worksheets/teacher-guides/pm25-safer-action-guide.html','./worksheets/teacher-guides/water-cycle-responsible-use-guide.html','./worksheets/teacher-guides/levers-make-work-easier-guide.html','./worksheets/teacher-guides/pulleys-gears-transfer-force-guide.html','./worksheets/teacher-guides/rights-responsibilities-digital-kindness-guide.html','./worksheets/teacher-guides/community-rules-shared-decisions-guide.html','./manifest.webmanifest'
];
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(CORE)));self.skipWaiting()});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key)))));self.clients.claim()});
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;event.respondWith(caches.match(event.request).then(cached=>cached||fetch(event.request).then(response=>{const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(event.request,copy));return response}).catch(()=>caches.match('./index.html'))))});
