import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const root=path.resolve(import.meta.dirname,'..');
const read=relative=>fs.readFileSync(path.join(root,relative),'utf8');
const exists=relative=>fs.existsSync(path.join(root,relative));
const slugs=[
'sleep-ready-brain','bones-joints-safer-posture','muscles-rest-movement','breathing-gas-exchange-safer-air','circulation-heart-safer-care','digestion-nutrients-responsible-food-information','excretion-kidneys-water-balance','nervous-system-brain-senses','immunity-germs-vaccines','hormones-growth-respectful-health-information','body-privacy-boundaries-consent-trusted-help','human-body-health-capstone',
'fact-opinion-ai-claims','personal-data-digital-footprints-consent','learning-from-data-and-bias','patterns-features-edge-cases','ai-decisions-confidence-human-escalation','recommendation-ranking-fair-choice','robots-sensors-fail-safe-systems','generative-ai-provenance-verification','image-recognition-errors-privacy','responsible-ai-capstone',
'pm25-safer-action','water-cycle-responsible-use','soil-erosion-conservation','waste-5r-lower-waste-system','household-energy-efficiency-responsible-choices','climate-weather-responsible-preparedness','ecosystems-biodiversity-responsible-observation','floods-droughts-community-resilience','noise-light-pollution-safer-design','chiang-rai-environmental-action-capstone',
'levers-make-work-easier','pulleys-gears-transfer-force','wheels-axles-designing-motion','structures-shapes-strength','materials-properties-responsible-selection','friction-surfaces-safer-motion','magnets-forces-safe-sorting','simple-circuits-energy-electrical-safety','heat-insulation-safe-container-design','community-engineering-design-capstone',
'rights-responsibilities-digital-kindness','community-rules-shared-decisions','media-public-information-evidence-checking','disagreement-dialogue-peaceful-resolution','community-institutions-responsible-participation','public-rules-fairness-reviewing-decisions','community-budgets-public-resources-transparent-choices','community-data-surveys-responsible-reporting','emergency-rumours-risk-communication-responsible-help','community-citizenship-action-capstone'];
const lessons=[
'subjects/human-body/sleep-ready-brain.html','subjects/human-body/bones-joints-safer-posture.html','subjects/human-body/muscles-rest-movement.html','subjects/human-body/breathing-gas-exchange-safer-air.html','subjects/human-body/circulation-heart-safer-care.html','subjects/human-body/digestion-nutrients-responsible-food-information.html','subjects/human-body/excretion-kidneys-water-balance.html','subjects/human-body/nervous-system-brain-senses-responsible-health-information.html','subjects/human-body/immunity-germs-vaccines-responsible-health-information.html','subjects/human-body/hormones-growth-respectful-health-information.html','subjects/human-body/body-privacy-boundaries-consent-trusted-help.html','subjects/human-body/human-body-health-capstone.html',
'subjects/ai-science/fact-opinion-ai-claims.html','subjects/ai-science/personal-data-digital-footprints-consent.html','subjects/ai-science/learning-from-data-and-bias.html','subjects/ai-science/patterns-features-edge-cases.html','subjects/ai-science/ai-decisions-confidence-human-escalation.html','subjects/ai-science/recommendation-ranking-fair-choice.html','subjects/ai-science/robots-sensors-fail-safe-systems.html','subjects/ai-science/generative-ai-provenance-verification.html','subjects/ai-science/image-recognition-errors-privacy.html','subjects/ai-science/responsible-ai-capstone-question-design-verify-explain.html',
'subjects/environment/pm25-safer-action.html','subjects/environment/water-cycle-responsible-use.html','subjects/environment/soil-erosion-conservation.html','subjects/environment/waste-5r-lower-waste-system.html','subjects/environment/household-energy-efficiency-responsible-choices.html','subjects/environment/climate-weather-responsible-preparedness.html','subjects/environment/ecosystems-biodiversity-responsible-observation.html','subjects/environment/floods-droughts-community-resilience.html','subjects/environment/noise-light-pollution-safer-environmental-design.html','subjects/environment/chiang-rai-environmental-action-capstone.html',
'subjects/maker-engineering/levers-make-work-easier.html','subjects/maker-engineering/pulleys-gears-transfer-force.html','subjects/maker-engineering/wheels-axles-designing-motion.html','subjects/maker-engineering/structures-shapes-strength.html','subjects/maker-engineering/materials-properties-responsible-selection.html','subjects/maker-engineering/friction-surfaces-safer-motion.html','subjects/maker-engineering/magnets-forces-safe-sorting.html','subjects/maker-engineering/simple-circuits-energy-electrical-safety.html','subjects/maker-engineering/heat-insulation-safe-container-design.html','subjects/maker-engineering/community-engineering-design-capstone.html',
'subjects/citizenship/rights-responsibilities-digital-kindness.html','subjects/citizenship/community-rules-shared-decisions.html','subjects/citizenship/media-public-information-evidence-checking.html','subjects/citizenship/disagreement-dialogue-peaceful-resolution.html','subjects/citizenship/community-institutions-responsible-participation.html','subjects/citizenship/public-rules-fairness-reviewing-decisions.html','subjects/citizenship/community-budgets-public-resources-transparent-choices.html','subjects/citizenship/community-data-surveys-responsible-reporting.html','subjects/citizenship/emergency-rumours-risk-communication-responsible-help.html','subjects/citizenship/community-citizenship-action-capstone.html'];
const worksheets=slugs.map(slug=>`worksheets/student/${slug}-a4.html`);
const guides=slugs.slice(1).map(slug=>`worksheets/teacher-guides/${slug}-guide.html`);
const scripts=['sleep-lesson','bones-posture-lesson','muscles-movement-lesson','breathing-air-lesson','circulation-heart-lesson','digestion-nutrients-lesson','kidneys-water-balance-lesson','nervous-system-lesson','immunity-vaccines-lesson','hormones-growth-lesson','body-privacy-consent-lesson','human-body-health-capstone-lesson','ai-claims-lesson','privacy-consent-lesson','data-bias-lesson','patterns-features-lesson','ai-confidence-lesson','recommendation-fair-choice-lesson','robots-fail-safe-lesson','generative-ai-provenance-lesson','image-recognition-privacy-lesson','responsible-ai-capstone-lesson','pm25-lesson','water-cycle-lesson','soil-erosion-lesson','waste-5r-lesson','household-energy-lesson','climate-weather-lesson','ecosystems-biodiversity-lesson','flood-drought-resilience-lesson','noise-light-pollution-lesson','chiang-rai-environmental-capstone-lesson','levers-lesson','pulleys-gears-lesson','wheels-axles-core','wheels-axles-assessment','structures-strength-lesson','materials-properties-lesson','friction-surfaces-lesson','magnets-sorting-lesson','simple-circuits-lesson','heat-insulation-lesson','community-engineering-capstone-lesson','citizenship-lesson','community-decisions-lesson','media-evidence-lesson','peaceful-dialogue-lesson','community-participation-lesson','public-rules-fairness-lesson','community-budget-lesson','community-data-survey-lesson','emergency-rumours-lesson','community-citizenship-capstone-lesson','learning-shell'].map(name=>`assets/js/${name}.js`).concat('service-worker.js');
const keys=['arshavin.sleep.lesson.v1','arshavin.humanbody.bones.v1','arshavin.humanbody.muscles.v1','arshavin.humanbody.breathing.v1','arshavin.humanbody.circulation.v1','arshavin.humanbody.digestion.v1','arshavin.humanbody.kidneys.v1','arshavin.humanbody.nervous.v1','arshavin.humanbody.immunity.v1','arshavin.humanbody.hormones.v1','arshavin.humanbody.bodyprivacy.v1','arshavin.humanbody.capstone.v1','arshavin.ai.claims.v1','arshavin.ai.privacy.v1','arshavin.ai.databias.v1','arshavin.ai.patterns.v1','arshavin.ai.confidence.v1','arshavin.ai.recommendation.v1','arshavin.ai.robots.v1','arshavin.ai.generative.v1','arshavin.ai.vision.v1','arshavin.ai.capstone.v1','arshavin.environment.pm25.v1','arshavin.environment.water.v1','arshavin.environment.soil.v1','arshavin.environment.waste.v1','arshavin.environment.energy.v1','arshavin.environment.climate.v1','arshavin.environment.biodiversity.v1','arshavin.environment.resilience.v1','arshavin.environment.noiselight.v1','arshavin.environment.capstone.v1','arshavin.maker.levers.v1','arshavin.maker.pulleysgears.v1','arshavin.maker.wheelsaxles.v1','arshavin.maker.structures.v1','arshavin.maker.materials.v1','arshavin.maker.friction.v1','arshavin.maker.magnets.v1','arshavin.maker.circuits.v1','arshavin.maker.heat.v1','arshavin.maker.capstone.v1','arshavin.citizenship.rights.v1','arshavin.citizenship.community.v1','arshavin.citizenship.media.v1','arshavin.citizenship.dialogue.v1','arshavin.citizenship.participation.v1','arshavin.citizenship.fairness.v1','arshavin.citizenship.budget.v1','arshavin.citizenship.data.v1','arshavin.citizenship.rumours.v1','arshavin.citizenship.capstone.v1'];
function check(name,fn){try{fn();console.log(`PASS ${name}`)}catch(error){console.error(`FAIL ${name}: ${error.message}`);process.exitCode=1}}
check('required files exist',()=>{[...lessons,...worksheets,...guides,...scripts,'index.html','assets/css/site.css'].forEach(file=>assert.ok(exists(file),file))});
check('JavaScript parses',()=>scripts.forEach(file=>new vm.Script(read(file),{filename:file})));
check('bilingual lesson shell structure',()=>lessons.forEach(file=>{const html=read(file);assert.match(html,/<html lang="th">/);assert.match(html,/<h1>[\s\S]*<br>[\s\S]*<span>/);assert.match(html,/data-learning-shell/);assert.match(html,/assets\/js\/learning-shell\.js/)}));
check('local links resolve',()=>{for(const file of ['index.html',...lessons,...worksheets,...guides]){const html=read(file),directory=path.dirname(file);for(const match of html.matchAll(/(?:href|src)="([^"#]+)"/g)){const target=match[1];if(/^(?:https?:|mailto:|data:)/.test(target))continue;assert.ok(exists(path.normalize(path.join(directory,target))),`${file} -> ${target}`)}}});
check('worksheets are exactly two A4 sheets',()=>worksheets.forEach(file=>{const html=read(file);assert.equal((html.match(/class="worksheet(?:\s|")/g)||[]).length,2,file);assert.ok(/@page\s*\{[\s\S]*size:\s*A4/.test(html)||/assets\/css\/site\.css/.test(html),file)}));
check('homepage and shell expose all lessons and keys',()=>{const homepage=read('index.html'),shell=read('assets/js/learning-shell.js');lessons.forEach(file=>assert.ok(homepage.includes(file),file));['HB-01','HB-02','HB-03','HB-04','HB-05','HB-06','HB-07','HB-08','HB-09','HB-10','HB-11','HB-12','AI-01','AI-02','AI-03','AI-04','AI-05','AI-06','AI-07','AI-08','AI-09','AI-10','ENV-01','ENV-02','ENV-03','ENV-04','ENV-05','ENV-06','ENV-07','ENV-08','ENV-09','ENV-10','MAKER-01','MAKER-02','MAKER-03','MAKER-04','MAKER-05','MAKER-06','MAKER-07','MAKER-08','MAKER-09','MAKER-10','CIT-01','CIT-02','CIT-03','CIT-04','CIT-05','CIT-06','CIT-07','CIT-08','CIT-09','CIT-10'].forEach(id=>assert.ok(shell.includes(id),id));keys.forEach(key=>{assert.ok(homepage.includes(key),key);assert.ok(shell.includes(key),key)})});
check('lesson scripts are local-only',()=>scripts.filter(file=>file.startsWith('assets/js/')&&!file.endsWith('learning-shell.js')).forEach(file=>assert.doesNotMatch(read(file),/fetch\(|XMLHttpRequest|WebSocket|sendBeacon/,file)));
check('offline precache',()=>{const sw=read('service-worker.js');[...scripts.filter(file=>file.startsWith('assets/js/')),...lessons,...worksheets,...guides].forEach(file=>assert.ok(sw.includes(`./${file}`),file));assert.match(sw,/arshavin-grade4-v\d+/)});
check('CIT-10 citizenship capstone',()=>{const material=read('subjects/citizenship/community-citizenship-action-capstone.html')+read('worksheets/teacher-guides/community-citizenship-action-capstone-guide.html')+read('worksheets/student/community-citizenship-action-capstone-a4.html');const script=read('assets/js/community-citizenship-capstone-lesson.js');['VOICE','evidence','dialogue','public institution','budget','survey','risk communication','trade-off','aggregate','political profiling','child-only escalation'].forEach(token=>assert.match(material,new RegExp(token,'i')));['canvasComplete','reviewComplete','quizComplete'].forEach(key=>assert.match(script,new RegExp(key)));assert.doesNotMatch(material,/draggable="true"/)});
check('HB-12 human body and health capstone',()=>{const material=read('subjects/human-body/human-body-health-capstone.html')+read('worksheets/teacher-guides/human-body-health-capstone-guide.html')+read('worksheets/student/human-body-health-capstone-a4.html');const script=read('assets/js/human-body-health-capstone-lesson.js');['WHOLE','body system','evidence','healthy routine','privacy','trusted help','no diagnosis','personal health record','body comparison','forced disclosure'].forEach(token=>assert.match(material,new RegExp(token,'i')));['systemsComplete','planComplete','quizComplete'].forEach(key=>assert.match(script,new RegExp(key)));assert.doesNotMatch(material,/draggable="true"/)});
if(process.exitCode)process.exit(process.exitCode);
