import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const root = path.resolve(import.meta.dirname, '..');
const read = relative => fs.readFileSync(path.join(root, relative), 'utf8');
const exists = relative => fs.existsSync(path.join(root, relative));
const slugs = [
  'sleep-ready-brain','bones-joints-safer-posture','muscles-rest-movement','breathing-gas-exchange-safer-air','circulation-heart-safer-care','digestion-nutrients-responsible-food-information',
  'fact-opinion-ai-claims','personal-data-digital-footprints-consent','learning-from-data-and-bias','patterns-features-edge-cases','ai-decisions-confidence-human-escalation',
  'pm25-safer-action','water-cycle-responsible-use','soil-erosion-conservation','waste-5r-lower-waste-system','household-energy-efficiency-responsible-choices',
  'levers-make-work-easier','pulleys-gears-transfer-force','wheels-axles-designing-motion','structures-shapes-strength','materials-properties-responsible-selection',
  'rights-responsibilities-digital-kindness','community-rules-shared-decisions','media-public-information-evidence-checking','disagreement-dialogue-peaceful-resolution','community-institutions-responsible-participation'
];
const lessons = [
  'subjects/human-body/sleep-ready-brain.html','subjects/human-body/bones-joints-safer-posture.html','subjects/human-body/muscles-rest-movement.html','subjects/human-body/breathing-gas-exchange-safer-air.html','subjects/human-body/circulation-heart-safer-care.html','subjects/human-body/digestion-nutrients-responsible-food-information.html',
  'subjects/ai-science/fact-opinion-ai-claims.html','subjects/ai-science/personal-data-digital-footprints-consent.html','subjects/ai-science/learning-from-data-and-bias.html','subjects/ai-science/patterns-features-edge-cases.html','subjects/ai-science/ai-decisions-confidence-human-escalation.html',
  'subjects/environment/pm25-safer-action.html','subjects/environment/water-cycle-responsible-use.html','subjects/environment/soil-erosion-conservation.html','subjects/environment/waste-5r-lower-waste-system.html','subjects/environment/household-energy-efficiency-responsible-choices.html',
  'subjects/maker-engineering/levers-make-work-easier.html','subjects/maker-engineering/pulleys-gears-transfer-force.html','subjects/maker-engineering/wheels-axles-designing-motion.html','subjects/maker-engineering/structures-shapes-strength.html','subjects/maker-engineering/materials-properties-responsible-selection.html',
  'subjects/citizenship/rights-responsibilities-digital-kindness.html','subjects/citizenship/community-rules-shared-decisions.html','subjects/citizenship/media-public-information-evidence-checking.html','subjects/citizenship/disagreement-dialogue-peaceful-resolution.html','subjects/citizenship/community-institutions-responsible-participation.html'
];
const worksheets = slugs.map(slug => `worksheets/student/${slug}-a4.html`);
const guides = slugs.slice(1).map(slug => `worksheets/teacher-guides/${slug}-guide.html`);
const scripts = [
  'sleep-lesson','bones-posture-lesson','muscles-movement-lesson','breathing-air-lesson','circulation-heart-lesson','digestion-nutrients-lesson','ai-claims-lesson','privacy-consent-lesson','data-bias-lesson','patterns-features-lesson','ai-confidence-lesson','pm25-lesson','water-cycle-lesson','soil-erosion-lesson','waste-5r-lesson','household-energy-lesson','levers-lesson','pulleys-gears-lesson','wheels-axles-core','wheels-axles-assessment','structures-strength-lesson','materials-properties-lesson','citizenship-lesson','community-decisions-lesson','media-evidence-lesson','peaceful-dialogue-lesson','community-participation-lesson','learning-shell'
].map(name => `assets/js/${name}.js`).concat('service-worker.js');
const keys = [
  'arshavin.sleep.lesson.v1','arshavin.humanbody.bones.v1','arshavin.humanbody.muscles.v1','arshavin.humanbody.breathing.v1','arshavin.humanbody.circulation.v1','arshavin.humanbody.digestion.v1',
  'arshavin.ai.claims.v1','arshavin.ai.privacy.v1','arshavin.ai.databias.v1','arshavin.ai.patterns.v1','arshavin.ai.confidence.v1',
  'arshavin.environment.pm25.v1','arshavin.environment.water.v1','arshavin.environment.soil.v1','arshavin.environment.waste.v1','arshavin.environment.energy.v1',
  'arshavin.maker.levers.v1','arshavin.maker.pulleysgears.v1','arshavin.maker.wheelsaxles.v1','arshavin.maker.structures.v1','arshavin.maker.materials.v1',
  'arshavin.citizenship.rights.v1','arshavin.citizenship.community.v1','arshavin.citizenship.media.v1','arshavin.citizenship.dialogue.v1','arshavin.citizenship.participation.v1'
];
function check(name, fn) { try { fn(); console.log(`PASS ${name}`); } catch (error) { console.error(`FAIL ${name}: ${error.message}`); process.exitCode = 1; } }
check('required files exist', () => {[...lessons,...worksheets,...guides,...scripts,'index.html','assets/css/site.css'].forEach(file=>assert.ok(exists(file),file));});
check('JavaScript parses', () => scripts.forEach(file => new vm.Script(read(file), { filename: file })));
check('bilingual lesson shell structure', () => lessons.forEach(file => {const html=read(file);assert.match(html,/<html lang="th">/);assert.match(html,/<h1>[\s\S]*<br>[\s\S]*<span>/);assert.match(html,/data-learning-shell/);assert.match(html,/assets\/js\/learning-shell\.js/);}));
check('local links resolve', () => {for(const file of ['index.html',...lessons,...worksheets,...guides]){const html=read(file),directory=path.dirname(file);for(const match of html.matchAll(/(?:href|src)="([^"#]+)"/g)){const target=match[1];if(/^(?:https?:|mailto:|data:)/.test(target))continue;assert.ok(exists(path.normalize(path.join(directory,target))),`${file} -> ${target}`);}}});
check('worksheets are exactly two A4 sheets', () => worksheets.forEach(file => {const html=read(file);assert.equal((html.match(/class="worksheet(?:\s|")/g)||[]).length,2,file);assert.ok(/@page\s*\{[\s\S]*size:\s*A4/.test(html)||/assets\/css\/site\.css/.test(html),file);}));
check('homepage and shell expose all lessons and keys', () => {const homepage=read('index.html'),shell=read('assets/js/learning-shell.js');lessons.forEach(file=>assert.ok(homepage.includes(file),file));['HB-01','HB-02','HB-03','HB-04','HB-05','HB-06','AI-01','AI-02','AI-03','AI-04','AI-05','ENV-01','ENV-02','ENV-03','ENV-04','ENV-05','MAKER-01','MAKER-02','MAKER-03','MAKER-04','MAKER-05','CIT-01','CIT-02','CIT-03','CIT-04','CIT-05'].forEach(id=>assert.ok(shell.includes(id),id));keys.forEach(key=>{assert.ok(homepage.includes(key),key);assert.ok(shell.includes(key),key);});});
check('lesson scripts are local-only', () => scripts.filter(file=>file.startsWith('assets/js/')&&!file.endsWith('learning-shell.js')).forEach(file=>assert.doesNotMatch(read(file),/fetch\(|XMLHttpRequest|WebSocket|sendBeacon/,file)));
check('offline precache', () => {const serviceWorker=read('service-worker.js');[...scripts.filter(file=>file.startsWith('assets/js/')),...lessons,...worksheets,...guides].forEach(file=>assert.ok(serviceWorker.includes(`./${file}`),file));assert.match(serviceWorker,/arshavin-grade4-v\d+/);});
check('HB-06 safeguards and completion', () => {const material=read(lessons[5])+read(guides[4])+read(worksheets[5]);const script=read('assets/js/digestion-nutrients-lesson.js');['digestion','peristalsis','absorption','serving'].forEach(term=>assert.match(material,new RegExp(term,'i')));assert.match(material,/ลำไส้เล็ก[\s\S]{0,160}ดูดซึมสารอาหารส่วนใหญ่|small intestine[\s\S]{0,160}most/i);assert.match(material,/ไม่.*ตัดสิน.*รูปร่าง|not.*judge.*bod/i);assert.match(material,/ไม่.*จำกัดอาหาร|not.*restrict/i);assert.match(material,/ไม่.*วินิจฉัย|not.*diagnos/i);['pathComplete','labelComplete','quizComplete'].forEach(key=>assert.match(script,new RegExp(key)));assert.doesNotMatch(material,/draggable="true"/);});
check('AI-05 confidence and oversight safeguards',()=>{const material=read(lessons[10])+read(guides[9])+read(worksheets[10]);const script=read('assets/js/ai-confidence-lesson.js');['confidence','abstain','human escalation','threshold'].forEach(term=>assert.match(material,new RegExp(term,'i')));assert.match(material,/confidence[^\n]{0,120}(?:not|ไม่)[^\n]{0,80}(?:guarantee|รับประกัน|correct|ถูก)/i);assert.match(material,/สิทธิ|rights/);assert.match(material,/สุขภาพ|health/);assert.match(material,/ทบทวนผล|challenge|review/i);['simulatorComplete','stakesComplete','quizComplete'].forEach(key=>assert.match(script,new RegExp(key)));assert.doesNotMatch(material,/draggable="true"/);});
check('ENV-05 energy, privacy and safety safeguards',()=>{const material=read(lessons[15])+read(guides[14])+read(worksheets[15]);const script=read('assets/js/household-energy-lesson.js');['energy','power','efficiency','energy label','standby'].forEach(term=>assert.match(material,new RegExp(term,'i')));assert.match(material,/กำลัง[\s\S]{0,180}เวลา|power[\s\S]{0,180}time/i);assert.match(material,/ไม่.*บิล|no.*bill/i);assert.match(material,/ไม่.*ที่อยู่|no.*address/i);assert.match(material,/ไม่.*ซ่อม.*ไฟ|not.*repair.*electrical/i);['flowComplete','choiceComplete','quizComplete'].forEach(key=>assert.match(script,new RegExp(key)));assert.doesNotMatch(material,/draggable="true"/);});
check('MAKER-05 materials, lifecycle and safety safeguards',()=>{const material=read(lessons[20])+read(guides[19])+read(worksheets[20]);const script=read('assets/js/materials-properties-lesson.js');['strength','flexibility','water resistance','durability','life cycle'].forEach(term=>assert.match(material,new RegExp(term,'i')));assert.match(material,/ไม่มีวัสดุ.*ดีที่สุด.*ทุกงาน|no material.*best.*every/i);assert.match(material,/เปลี่ยนทีละหนึ่งตัวแปร|change one variable/i);assert.match(material,/ใช้ซ้ำ|reuse/i);assert.match(material,/ซ่อม|repair/i);assert.match(material,/ไม่รับรอง|does not certify/i);assert.match(material,/ผู้ใหญ่.*ตัด|adult.*cut/i);['matrixComplete','designComplete','quizComplete'].forEach(key=>assert.match(script,new RegExp(key)));assert.doesNotMatch(material,/draggable="true"/);});
check('CIT-05 participation, privacy and safeguarding',()=>{const material=read(lessons[25])+read(guides[24])+read(worksheets[25]);const script=read('assets/js/community-participation-lesson.js');['community institution','public service','responsibility','evidence','participation'].forEach(term=>assert.match(material,new RegExp(term,'i')));['Pinpoint','Ask','Take relevant evidence','Hear back'].forEach(term=>assert.match(material,new RegExp(term,'i')));assert.match(material,/ไม่รับคำร้องจริง|no real complaint/i);assert.match(material,/ความคิดเห็นทางการเมือง|political/i);assert.match(material,/ผู้ใหญ่|adult/i);assert.match(material,/คนแปลกหน้า|stranger/i);['pathwayComplete','evidenceComplete','quizComplete'].forEach(key=>assert.match(script,new RegExp(key)));assert.doesNotMatch(material,/draggable="true"/);});
if(process.exitCode)process.exit(process.exitCode);